version: "3.9"

services:
  http:
    image: golang:1.17
    volumes:
      - $GOPATH/pkg/mod:/go/pkg/mod
      - ./:/src/go
    working_dir: /src/go/webserver/http
    environment:
      - PORT=8080
    command: go run main.go
    ports:
      - 8080:8080

  echo:
    image: golang:1.17
    volumes:
      - $GOPATH/pkg/mod:/go/pkg/mod
      - ./:/src/go
    working_dir: /src/go/webserver/echo
    environment:
      - PORT=8081
    command: go run main.go
    ports:
      - 8081:8081

  gin:
    image: golang:1.17
    volumes:
      - $GOPATH/pkg/mod:/go/pkg/mod
      - ./:/src/go
    working_dir: /src/go/webserver/gin
    environment:
      - PORT=8082
    command: go run main.go
    ports:
      - 8082:8082
    depends_on:
      - kafka

  grpc:
    image: golang:1.17
    volumes:
      - $GOPATH/pkg/mod:/go/pkg/mod
      - ./:/src/go
    working_dir: /src/go/webserver/grpc
    environment:
      - PORT=6565
    command: go run main.go
    ports:
      - 6565:6565

  sarama-consumer:
    image: golang:1.17
    volumes:
      - $GOPATH/pkg/mod:/go/pkg/mod
      - ./:/src/go
    working_dir: /src/go/consumer
    command: go run main.go
    depends_on:
      - kafka


  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zipkin:
    image: openzipkin/zipkin:2.23
    ports:
      - 9090:9411

  jaeger:
    image: jaegertracing/all-in-one:1.31
    environment:
      - JAEGER_AGENT_HOST=jaeger
    ports:
      - 9091:16686